#!/bin/bash
# Run clang-tidy across every C source file the project owns — that is,
# src/*.c and examples/*.c — using the compile_commands.json that CMake
# produces in build/. Third-party trees (build/_deps/llhttp,
# build/_deps/mbedtls) are not linted: they have their own style and
# their own bugs to worry about.
#
# NOT run by default from tests/test_all.sh — clang-tidy takes several
# seconds per file and holds up the fast feedback loop. Invoke it
# directly when reviewing a change:
#     bash scripts/tidy.sh            # lint everything
#     bash scripts/tidy.sh src/conn.c # lint one file
#     bash scripts/tidy.sh --fix      # apply tidy's suggested fixes in place
set -uo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

if ! command -v clang-tidy >/dev/null 2>&1; then
    echo "clang-tidy not installed — skipping"
    echo "  install with: sudo apt install clang-tidy   (Debian/Ubuntu)"
    echo "               sudo dnf install clang-tools-extra   (Fedora/RHEL)"
    exit 0
fi

# compile_commands.json is generated by CMake when CMAKE_EXPORT_COMPILE_COMMANDS
# is on. Our top-level CMakeLists.txt sets it; a fresh configure is enough.
if [ ! -f build/compile_commands.json ]; then
    echo "build/compile_commands.json missing — running cmake configure"
    cmake -S . -B build >/dev/null || { echo "cmake configure failed" >&2; exit 2; }
fi

# Parse args: --fix triggers in-place rewrites, otherwise list-of-paths
# (empty ⇒ all own-source files).
FIX_FLAG=""
FILES=()
for arg in "$@"; do
    case "$arg" in
        --fix) FIX_FLAG="--fix" ;;
        -*) echo "unknown flag: $arg" >&2; exit 2 ;;
        *)  FILES+=("$arg") ;;
    esac
done

if [ "${#FILES[@]}" -eq 0 ]; then
    shopt -s nullglob
    FILES=(src/*.c examples/*.c)
fi

echo "clang-tidy $(clang-tidy --version | awk '/version/ {print $NF; exit}')"
echo "linting ${#FILES[@]} file(s)"
[ -n "$FIX_FLAG" ] && echo "  (applying fixes in place)"
echo

TOTAL_WARN=0
FAIL_FILES=()
for f in "${FILES[@]}"; do
    # --quiet drops the "N warnings generated" banner, but we still
    # count real warning lines from our own tree.
    out=$(clang-tidy -p build --quiet $FIX_FLAG "$f" 2>&1) || true
    # Only count warnings that point at our own files — the header
    # filter already excludes system and _deps headers, but clang-tidy
    # occasionally emits notes from transitive includes.
    n=$(echo "$out" | grep -cE "^${REPO_ROOT}/(src|include|examples)/.*(warning|error):" || true)
    if [ "$n" -gt 0 ]; then
        echo "=== $f ($n finding(s)) ==="
        echo "$out" | grep -E "(warning|error):" | sed 's/^/  /'
        echo
        TOTAL_WARN=$((TOTAL_WARN + n))
        FAIL_FILES+=("$f")
    fi
done

echo "=== summary ==="
if [ "$TOTAL_WARN" -eq 0 ]; then
    echo "clang-tidy: no findings across ${#FILES[@]} file(s)"
    exit 0
fi

echo "clang-tidy: $TOTAL_WARN finding(s) across ${#FAIL_FILES[@]} file(s)"
printf '  %s\n' "${FAIL_FILES[@]}"
exit 1
